### ISSUE TITLE
Server crashes when players join

### ISSUE THREAD

**Issue by AlphaMSq** [LiteLDev/MovingLight#1]
BDS - 1.19.61
LL - 2.10.0
Error -
[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- Minidump generated in Directory ./logs/Crash

[StackTrace] Function abort at 0x7FFC871B2820  [ucrtbase.dll<6.2.19041.789>]
[StackTrace] Function terminate at 0x7FFC871B1F80  [ucrtbase.dll<6.2.19041.789>]
[StackTrace] Function gsl::details::terminate at 0x7FF6806EBFD0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function Actor::getPersistentComponent<ActorUniqueIDComponent const > at 0x7FF681676AB0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function Actor::getUniqueID at 0x7FF6816986F0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function onPostInit at 0x7FFC57745FA0  [MovingLight.dll]
[StackTrace] Function entt::basic_storage<ActorOwnerComponent,EntityId,std::allocator<ActorOwnerComponent>,void>::pop at 0x7FF6808B5EA0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function entt::basic_registry<EntityId,std::allocator<EntityId> >::destroy at 0x7FF680BFBA70  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function EntityRegistry::_destroyEntity at 0x7FF680BFBA30  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function OwnerStorageEntity::~OwnerStorageEntity at 0x7FF680AAFEC0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function ActorGarbageCollector::update at 0x7FF681B60AD0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function Level::tick at 0x7FF68195F970  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function ServerLevel::tick at 0x7FF680F5C430  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function ???????? at 0x7FFC4F3C284E  [LiteLoader.Js.dll<2.10.0.0>]
[StackTrace] Function ???????? at 0x7FFC2F4A56B0  [LiteLoader.Lua.dll<2.10.0.0 PRIVATEBUILD>]
[StackTrace] Function Schedule::nextTick at 0x7FFC510B6D30  [LiteLoader.dll<2.10.0.0>]
[StackTrace] Function GameSession::tick at 0x7FF681860350  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function Minecraft::update at 0x7FF681643AD0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function ServerInstance::_update at 0x7FF680ED9C30  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function <lambda_eea4b55ce73e04688a1edc3fabfb52cb>::operator() at 0x7FF680ED7FC0  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_eea4b55ce73e04688a1edc3fabfb52cb> >,0> at 0x7FF680ED4480  [bedrock_server_mod.exe<1.19.61.01>]
[StackTrace] Function configthreadlocale at 0x7FFC87161B20  [ucrtbase.dll<6.2.19041.789>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFC88E57600  [KERNEL32.DLL<6.2.19041.2364>]
[StackTrace] Function RtlUserThreadStart at 0x7FFC89362680  [ntdll.dll<6.2.19041.2130>]

**Comment by Redbeanw44602** [comment]
try latest release.

**Comment by AlphaMSq** [comment]
Works
